spring:
   profiles:
      active: dev
   datasource:
      username: dev
      password: dev
      url: jdbc:oracle:thin:@localhost:1521:dev
      driver-class-name: oracle.jdbc.driver.OracleDriver
   freemarker:
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
   redis:
      database: 0
      host: localhost
      port: 6379
      password: null
      pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
      timeout: 3000
   mail:
      from: pd_test@163.com
      host: smtp.163.com
      username: pd_test@163.com
      password: JLQPFNTZVFXWUMJJ
      default-encoding: UTF-8
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
                  
lance:
   mail:
      sender: pd_test@163.com
server:
   port: 8080
mybatis-plus:
   mapper-locations: classpath*:mapper/*.xml
   type-aliases-package: com.pd.businessobject