spring:
    profiles:
        active: dev
    datasource:
        username: dev
        password: dev
        url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver

server:
    port: 8080

mybatis:
    mapper-locations: classpath*:mapper/*.xml