spring:
    profiles:
        active: dev
    datasource:
        username: dev
        password: dev
        url: jdbc:oracle:thin:@localhost:1521:dev
        driver-class-name: oracle.jdbc.driver.OracleDriver
    redis:
        database: 0
        host: 192.168.0.155
        port: 6379
        password: 
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
        timeout: 0
       

server:
    port: 8080

mybatis:
    mapper-locations: classpath*:mapper/*.xml